### PR TITLE
[#18] Provide slf4j 2 compatibility - implement service loader

### LINKED ISSUE #18: Provide implementation for slf4j-api 2.0
slf4j 2.0 uses ServiceLoader mechanism instead of older loading mechanism.

This makes it compatible with Java 9 module system.

See https://www.slf4j.org/manual.html
https://github.com/amperity/dialog/pull/11#issuecomment-1302321624

### LINKED ISSUE #34: [BUG] prep-ing the library fails because it wants JDK-8
Hi, 

I'm using the slf4j branch in a project and I tried to prep it by running `clojure -X:deps prep :aliases '[:dev]'`  .
However it fails because I am running on jdk-17 and it requires jdk-8.

This makes the library not usable via deps git integration. 

The warning should be kept, but the exit should be removed IMO.
For my case it makes no sense - I am building it for my app - all app is built with jdk-17.
The check makes sense only for people doing releases.  

```
(defn javac
  "Compile Java source files in the project."
  [_]
  (let [java-version (System/getProperty "java.version")]
    (when-not (str/starts-with? java-version "1.8")
      (binding [*out* *err*]
        (println "Dialog should be compiled with Java 1.8 for maximum"
                 "compatibility; currently using:" java-version))
      (System/exit 1)))
```

Before:
```
bb prep
Downloading: org/clojure/clojure/maven-metadata.xml from central
Downloading: org/clojure/clojure/maven-metadata.xml from clojars
Downloading: org/clojure/clojure/maven-metadata.xml from oss-snapshots-repo
Prepping amperity/dialog in /home/ieugen/.gitlibs/libs/amperity/dialog/d6569524ddc6f93eee9076054d9aa7887c8555fc
Dialog should be compiled with Java 1.8 for maximum compatibility; currently using: 17.0.5
Execution error (ExceptionInfo) at clojure.tools.deps/prep-libs!$fn (deps.clj:711).
Prep function could not be resolved: build/javac

Full report at:
/tmp/clojure-17842702112232980049.edn
Error while executing task: prep
```

After:
```
bb prep
Checking out: https://github.com/ieugen/dialog at 50fdfd3bacf4e86f1b82b3a9a3ea5e14fdbf974f
Prepping amperity/dialog in /home/ieugen/.gitlibs/libs/amperity/dialog/50fdfd3bacf4e86f1b82b3a9a3ea5e14fdbf974f
Dialog should be compiled with Java 1.8 for maximum compatibility; currently using: 17.0.5
✓ prep
```

### PR DESCRIPTION
**Pull request by ieugen**
Fixes #18 
Fixes #34

* Implemented service loader
* All tests pass
* clojure tools-logging works with slf4j-api 2.0 https://clojure.atlassian.net/browse/TLOG-28 and https://ask.clojure.org/index.php/12390/provide-slf4j-2-0-factory-for-tools-logging 
   
TODO (need help): 
* Check service loader implementation
* Restore the older logging bridges - jul and commons logging

### CODE REVIEW

**Comment by ieugen** [comment]
@greglook : 
I've fixed the check for slf4j version but I ran into another one.
I need your help figuring this one out.

```shell
Found uncommented reference to 'requiring-resolve' in logger classes:
src/java/dialog/logger/DialogServiceProvider.java:        IFn resolve = RT.var("clojure.core", "requiring-resolve");
``` 
So this check is failing because I put the Service Provider implementation in dialog/ dir.
I took the code from the previous StaticLoggerBinder implementation which was in a different path.
The other path was not searched by `test/check-dynamic-resolves` 

```shell
readonly MATCHES=$(grep -RE '^ *IFn.*"requiring-resolve"' src/java/dialog)
```
Why is the check here anyway?
I don't know what solution to adopt in fixing this.

**Comment by ieugen** [comment]
I chose to move the service provider class to package `dialog.impl` and update the check to look into `dialog/logger`

**Comment by greglook** [comment]
The purpose of that test is to make sure that Dialog doesn't ship with a significant performance penalty that is caused by a development-time affordance. In the normal case in the current implementation, the `StaticLoggerBinder` is responsible for loading the dialog namespaces and resolving the various function vars which the Java code needs to hook into Clojure:
https://github.com/amperity/dialog/blob/3933260fec9c88068cf091aa47d6fd8999194499/src/java/org/slf4j/impl/StaticLoggerBinder.java#L53-L63
This should only happen _once_ in a real deployment with dialog, because locking the namespace loading monitor and re-resolving the var on every single logging call would be extremely expensive and slow. Those functions are then passed to the `DialogFactory` and then into each `DialogLogger`:
https://github.com/amperity/dialog/blob/3933260fec9c88068cf091aa47d6fd8999194499/src/java/org/slf4j/impl/StaticLoggerBinder.java#L69-L70
https://github.com/amperity/dialog/blob/3933260fec9c88068cf091aa47d6fd8999194499/src/java/dialog/logger/DialogFactory.java#L57-L58
However, as you can see, loggers are cached, so when you're actually developing Dialog itself, this can be really annoying as it causes you to need to restart the REPL process to pick up changes, even to Clojure code. So there are some commented-out blocks like this, which you can enable to make hot-reloading work again, _while you're working on Dialog_.
https://github.com/amperity/dialog/blob/3933260fec9c88068cf091aa47d6fd8999194499/src/java/dialog/logger/DialogLogger.java#L130-L133
The test script is ensuring that these blocks are never left uncommented on accident.

**Comment by ieugen** [comment]
hi @greglook . we are using apache jena in our project and it's bound to slf4j-api 2.0. 
I'm going to look into using dialog with the API for our project (was on todo for some time).

Any chance we can get this PR merged in dialog?
More and more projects will most likely move to slf4j-api 2.0 since there are really no downsides. 
And the API is backward compatible. 
Just need to make sure any implementations for < 2.0 are on the classpath.

**Review by greglook — APPROVED** [review]
Thanks for writing and testing this! Let's get this merged and I'll get the library ready for 2.x. 🎉

**Pull request merged**
