### PR TITLE
Add :padding option to simple and pretty formatters

### PR DESCRIPTION
**Pull request by greglook**
For simple projects with short class/logger names, the default padding amounts can result in quite a lot of whitespace. This PR adds a `:padding` option which the `:simple` and `:pretty` formatters will check to disable padding of the thread, level, and logger fields.

### CODE REVIEW

**Comment by derekslager** [comment]
Option is working but I observe an extra space between logger name and log message which I wouldn't have expected, not sure if that's by design.

image

**Comment by greglook** [comment]
Yeah, the double-space between the logger and the message is intentional. The goal is to help visually separate the message from the rest of the preceding fields.

**Comment by derekslager** [comment]
Got it -- glancing around it looks like default configs of other logging tools use " - " as a separator, might be reasonable to borrow that simply because it's familiar and many people would like a "drop in" replacement.

**Comment by greglook** [comment]
I'm a little averse to using `-` because that's already used by the formatting code to indicate a [missing field](https://github.com/amperity/dialog/blob/010e344e03e6dc27d04c56850b9c675e7fda2b7b/src/clojure/dialog/format/simple.clj#L47-L48) in some places.

**Review by drewinglis — APPROVED** [review]
I don't really have a strong opinion, but the code looks good.

**Pull request merged**
